### ISSUE TITLE
Not working with Houdini Indie 20.5.332 / Blender 4.2.1

### ISSUE THREAD

**Issue by noc2art** [Limbicnation/blender2houdini-exporter#14]
Everything's set up to the tee and no Juice :( Upon hitting the 'Send to Houdini' button, a Houdini session starts with nothing in Obj context.

What gives?

![image](https://github.com/user-attachments/assets/cf79d185-1230-4c22-a281-7bfabae265d0)

**Comment by noc2art** [comment]
Btw, you didn't mention in the installation instructions where **houdini_import_fbx.py**, **houdini_reload_fbx.py** and **launch_blender.py** are supposed to go. I also watched your demo video, you don't make any references to these .py files there at all. Maybe that's the culprit in my case?

**Comment by Limbicnation** [comment]
@noc2art Thanks for your interest in the addon!

I've updated the repository with a fix to ensure subprocess and path handling work properly on Windows. Please pull the latest [changes](https://github.com/Limbicnation/blender2houdini-exporter/commit/184e5cfd583762713e31a55fd480b3c38ff3ec22).

Make sure your Houdini version and FBX model file paths are valid. Since I'm currently on Linux, I haven't fully tested this on Windows yet, so any feedback from your side would be appreciated.

The `houdini_import_fbx.py` and `houdini_reload_fbx.py` scripts are part of the Houdini shelf tools (see attachments).

<p align="center"> <img src="https://github.com/user-attachments/assets/5866bacf-a424-4a38-98c4-de398872e7af" width="45%" /> <img src="https://github.com/user-attachments/assets/17e57dcb-ca44-4f04-b0b9-f6e98862519c" width="45%" /> </p>

I'll continue refining the tool to make it more robust and user-friendly. Thanks again for the feedback!

**Comment by noc2art** [comment]
Hi there;

Thanx for the fix, the 'send to Houdini' function from Blender works fine now. But there are certain inherent quirks that I feels I must point out;

- The geo node that contains the file node that calls the exported fbx object resides in a subnet named "b2h_export_fbx" which honestly seems a tad redundant. I believe it would be sufficient for the geo node to be placed at obj level directly.
- Secondly, the file node is created locked which is also redundant imo.
- Third, the 'Reload model' shelf tool simply doesn't work, ie does not refresh any changes to the model made in Blender. Maybe that tool is also redundant as I can do so by clicking on the "Reload Geometry' button.
